### PR TITLE
 Cannot edit a proposal #1 

### PR DESCRIPTION
**Pull request by jemagee**
Hopefully this goes over more smoothly then what I tried previously.  I hope that I wrote the BDD tests in a way that's pleasing.  It took me a bit to understand it (honestly, It feels a bit unnatural at first) but I think i got the swing of it in regards to writing the steps and using existing steps.  Presuming my feature test is written properly it does pass.

### CODE REVIEW

**Comment by nodunayo** [comment]
Hey @jemagee!

Sorry I haven't had a chance to look at these yet. Been very busy at work and home.

Will look at these by the end of the week, I hope. :-)

**Comment by jemagee** [comment]
Trust me, it’s not a big deal, I know how busy things get when you’re working and doing other stuff, heck I can barely do basic commits on my graphics side at this point :)
There’s no rush, and i’m not overly  neurotic about it, just the usual levels of neurotic :)

**Comment by nodunayo** [comment]
Hey John,

I think this looks really good. Wonderful first Cucumber attempt. :-)

A few minor points:

*  Perhaps we can move the 'Edit proposal' button to the end of the proposal, rather than under the 'Submissions' heading. What do you think?

* Cucumber scenarios typically have only one 'Given', 'When' and 'Then' clause, with others beginning with 'And', as you've pretty much done! Only thing, can you change line 5 of `editing_proposals.feature` to start with an 'And'?

* Your indenting in `step_definitions/editing_proposals.rb` seems to be set to 4 or so. Can we change it to 2 spaces?

Thanks!

**Comment by jemagee** [comment]
Hi

Sorry it took a couple days to get to, converting from an old version of microsoft navision to quickbooks enterprise when the consultant you depended on did everything wrong they said they did right can be extremely stressful.

I believe I corrected all the points you had elucidated a few days ago...though I did it directly within the repository on my github page (as a sort of test to see if that works) and it seems to have taken.  Hopefully this takes

**Comment by nodunayo** [comment]
Great work, John! I handled the merge conflict on the command line. All is now pushed and deployed! Thanks a lot. :-)

**Pull request closed without merging**
