### PR TITLE
setup docker to run the project

### PR DESCRIPTION
**Pull request by CrowdHailer**
This PR allows the project to be started in docker.
To start run `docker-compose up` should do the same as all the existing startup steps.

This will help me tackle #124 but I don't mind if it stays on a branch for my own use.

`docker-compose run app bundle exec rspec` will run all the tests.

~~**Current status** I have all the test running but am struggling to access the application from outside the docker container. Not sure if it's something to do with binding to 127.0.0.0 only or if localhost also works~~
Fixed by binding to `0.0.0.0`

### CODE REVIEW

**Comment by nodunayo** [comment]
Is it possible to get the tests passing using `bundle exec rspec` on this branch too,  because the build is failing?

**Comment by CrowdHailer** [comment]
I think I need to work out the configuration of the db host so that it's set to db only when running in docker.

**Comment by nodunayo** [comment]
Also, would you be able to add a little text in the `README` for anyone else wanting to run the site via Docker? Thank you!

**Comment by CrowdHailer** [comment]
Sure, 

I think there are two ways to use docker here.
1. as is with docker-compose to startup postgres and reach it through the networks, but needs a solution to configuring db url that I don't have yet
2. Just use a single container and instal postgres in it. Not how i would normally do it but might make sense because then it would be identically to running locally.

**Comment by nodunayo** [comment]
Right! I guess it's best to set it up how others can easily make use of it.

**Comment by nodunayo** [comment]
Thank you, Peter!

**Comment by nodunayo** [comment]
This PR is no longer relevant, right?

**Pull request closed without merging**
