### PR TITLE
Fix migration for PR 66

### PR DESCRIPTION
**Pull request by flyinggrizzly**
Migration now tries to find an Event object before instantiating on `up`

This allows migration to continue when an event has multiple instances. 

See also https://github.com/nodunayo/speakerline/pull/66#discussion_r168101032

### before pulling down latest changes (with `--force`)

1. seed the DB on the feature branch (it creates events with multiple instances which we can use to replicate the situation on staging)
2. roll back the last migration: `bin/rails db:rollback STEP=1`--this sets it so we have multiple old events with the same name but different years
3. try to migrate forward again, get failure

### after pulling down latest changes

repeat as above, but the migration will succeed because it will try to find an existing event before attempting to instantiate it

### CODE REVIEW

**Comment by nodunayo** [comment]
Just looking at this now..

FYI — didn't have to use `--force` to pull down the latest changes...

**Comment by flyinggrizzly** [comment]
I think I wrote that before resolving the merge conflict in the web app (airport)... which added another commit to the history so it no longer diverged

**Comment by nodunayo** [comment]
Yay, merged and shipped!!

Thank you, @flyinggrizzly. This was wonderful.

Thank you so much for your patience. Going through a few things right now so I really appreciate it.

Speak soon,

Nadia

**Comment by flyinggrizzly** [comment]
Anytime, and no worries! And thank you for your patience with me, and the support and feedback. 

I’ll poke through some of the other issues in a bit too. And I’ll see you at Bath Ruby!

**Comment by nodunayo** [comment]
Oh, yay! Exciting — get to meet my number 1 contributor in the flesh! And thank you for the feedback!

As an FYI, I'll be working on the ability to delete submissions and the design for that next, so don't worry about that piece. I've also got to sort out some config stuff like SSL and think about site backups soon.

Speak soon!

**Pull request merged**
