### PR TITLE
Title box extend

### PR DESCRIPTION
**Pull request by olwend**
#### What does this PR do?
'title' uses skeleton css class so is as long as view port allows
##### Why was this work done? Is there a related Issue?
https://github.com/nodunayo/speakerline/issues/43#### Where should a reviewer start?

#### Are there any manual testing steps?
Enter proposal titles of various lengths/ formats 
---

#### Screenshots
screen shot 2017-12-03 at 15 44 07

#### Database changes
db/schema.rb is changed by install as Im using Rails 5.1.2

### CODE REVIEW

**Comment by nodunayo** [comment]
Hi Olwen,

Thanks for this!

I've subsequently committed the db changes.

Is it possible that you squash the first two commits into one and get rid of the DB changes? You can rebase/squash on your fork and that should automatically update the PR.

Sorry to be a pain!

**Comment by olwend** [comment]
Hi Nadia,

You're not a pain. It's been a pleasure to have a go and get back to Rails.
Yes I'll squash and remove dB change, I can rebase branch too against the
updated master by pulling into the fork. I won't have a chance until
tonight.
Thanks

Olwen

**Comment by nodunayo** [comment]
Fantastic, Olwen. Thanks. 

Have a great Monday.

**Comment by nodunayo** [comment]
Merged and shipped! 😁

**Pull request merged**
