### PR TITLE
Changing Year Take Two

### PR DESCRIPTION
**Pull request by jemagee**
So I did it over this time including an up and down method that saves all the year information ***before*** doing anything, associated with id's, and then repopulates the year attribute for each record.  Admittedly, if this is a testable concept, I have no idea how to test it, but logically it should work, I think...if not, I'm sorry

### CODE REVIEW

**Comment by nodunayo** [comment]
Again, thank you for this! Will have a look soon. :-)

**Comment by nodunayo** [comment]
Hey John!

This looks like it does handle existing records. I'm going to set up a staging site over the next few days and do a dry run of this to check it works. :-)

**Comment by jemagee** [comment]
well I do hope it works - never really thought about doing ‘stuff’ in a migration beyond the migration itself so hopefully i did it right

**Comment by nodunayo** [comment]
This doesn't seem to work.

I'm getting the following:

```
= 20170307032721 ChangeYearToInteger: migrating ==============================
-- remove_column(:events, :year)
   -> 0.0070s
-- add_column(:events, :year, :integer, {:null=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "year" contains null values
: ALTER TABLE "events" ADD "year" integer NOT NULL
```

I'll look into it.

**Comment by nodunayo** [comment]
I think we need to allow the `year` column to be null first, and then later add a migration to require that column to be populated.

**Comment by nodunayo** [comment]
Yes, that seems to work!

**Comment by jemagee** [comment]
Yes, that makes sense and i realize I could have even written the migration properly to handle that if i thought it through.  Apologies for that, i’ll try and do better on the next one

**Comment by nodunayo** [comment]
Hey John,

I was playing around with this locally and discussing it with @theozaurus, who I work with. There are some things that we need to improve on the migration before we run it on the production site.

Using the Ruby and the ActiveRecord API to solve the problem causes a few subtle issues:

 - We become tightly coupled to the API of the Event object. This is not ordinarily a problem, but as migrations tend to exist for a long time and they should not be edited, any change in the Event API around the `pluck`, `find` and `update_attributes!` methods will mean the migration has to be refactored.

- The migration downloads and then uploads all of the data locally, which is an expensive operation that could be kept entirely in the database. Although not an issue now, this could be a huge amount of data.

- There is a risk that after dumping the data to local memory and dropping the column from the DB the computer crashes. This means you will lose any event/year information that you've downloaded and will have also lost the database column. The database should defend against this by using a transaction, but we shouldn't assume that in this migration, particularly when there is an easy way around it!

Turns out you were right with your initial suggestion of using SQL and that blog post was a very good find. That deals with all of the above considerations.

The downside to SQL is that you become tightly coupled to the type of SQL the database understands. I think this is a lower risk as changing databases is likely to involve a lot of migration rework anyway.

@theozaurus suggests as his preferred basic pattern for doing these types of migrations:

- Add the new column (perhaps named <column>_new)
- Get the data into the new column from the old column, using SQL if possible (pushes the work onto the DB which is very good at these types of things)
- Drop the old column
- Rename the new column to whatever the old column was called

This way if the migration fails for any reason, you will never lose any data.

I'm going to have a go at rewriting this migration using the tip in that blog post you sent. I'll let you know how I get on.

How does that sound?

Nadia

**Comment by jemagee** [comment]
From the parts that I did understand (the tight coupling is a bit beyond my understanding at this time) it makes total sense.  I’m not sure how to run SQL in the migration unless you’re just talking about using the raw SQL within the migration itself, it’s a simple update statement without even a conditional but probably need to ‘cast’ the string as an integer if that is something postgres will do….all in all the logic makes sense to me I think :)

**Comment by nodunayo** [comment]
Okay, let me try and explain what tight coupling is! 

If A is tightly coupled to B, then when you change A, you most likely have to change B too. Therefore, when you have a lot of objects or APIs that are tightly coupled in your software, making changes and maintenance is a nightmare.

So, if the Event class changed in any way and it no longer responded to methods that are called in it in the migration, then we'll have to (remember to) go and change the migration. With SQL (yes, you can use SQL within the migration) it doesn't matter which methods the `Event` class responds to (its API). The migration will still work.

Does that help a bit?

**Pull request merged**
