### PR TITLE
Issue #63 Development seeds file

### PR DESCRIPTION
**Pull request by JulieLev**
#### What does this PR do?
Issue #63 Adds development seeds file using stympy/faker gem.

##### Why was this work done? Is there a related Issue?
Save development time by providing fake data to work with.

#### Where should a reviewer start?
Review code changes then run: 
``bundle exec rake db:setup``
But note - this will overwrite all existing development data!

#### Are there any manual testing steps?
Visual check of data only.

---

#### Screenshots
None.

#### Deployment instructions
See above.

#### Database changes
None.

#### New ENV variables
None.

### CODE REVIEW

**Comment by JulieLev** [comment]
I'll be interested in your response, this is learning-by-doing in action!

**Comment by nodunayo** [comment]
Thanks, @JulieLev!

Will have a look as soon as I can.

**Comment by andrew** [comment]
Looking great @JulieLev! I like the use of `Faker::Hacker` to make some cool copy!

**Comment by nodunayo** [comment]
Hi @JulieLev,

This looks great (and fun!)

I hadn't seen the `faker` gem used before and it wasn't what I was expecting when I suggested the `seeds.rb` issue —  I thought you'd add some `create` calls in the file directly. That's what I would have done.

I asked @andrew for his feedback because I didn't want my inexperience to lead me to suggest that this was overcomplicated — when it was in fact fine. I was concerned by the inclusion extra dependency.

Anyway, I'm happy with this and you've taught me something new! I like the creativity of your approach, and how you've thought through linking up proposals, events, and submissions.

Will be merging in now.

☺️

**Comment by nodunayo** [comment]
Also, great work on thinking to add to the `README.md`.

I forgot that I'd spotted an error — your link won't work as the link text has to exactly equal the title text. I'll change it now!

**Comment by JulieLev** [comment]
Thank you @nodunayo and @andrew,

I'd never used the faker gem either. I did add create calls in the file initially to make sure I got the associations right then refactored it using the gem which was entirely experimental and yes, it was  fun too! 

I also learned how to squash commits...

Many thanks for your encouragement too - this is my first proper, accepted open source PR and has provided a much-needed boost to my confidence! I really appreciate the time you've taken to review it (and fix the link on the README!). 

😃

**Comment by nodunayo** [comment]
Yay, @JulieLev!

Congrats on your first one — and another will follow very soon with the columns on the Speaker Index page!

I'm glad you're feeling encouraged and that this has given you a confidence boost! You're great and you communicate really well across the PRs.

Thanks,

Nadia

😊

**Comment by JulieLev** [comment]
❤️

**Pull request merged**
