### PR TITLE
Add recapture to proposals#create form

### PR DESCRIPTION
**Pull request by andrew**
Adds some basic spam protection without requiring a login system.

Uses the excellent recapture gem: https://github.com/ambethia/recaptcha

You'll need to get an API key for the service here: https://www.google.com/recaptcha/admin

And then set the site and secret keys as environment variables on heroku:

```
RECAPTCHA_SITE_KEY=6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
RECAPTCHA_SECRET_KEY=6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx
```

Looks like this:
screen shot 2017-05-29 at 5 27 04 pm

~~One broken test to fix  before merging.~~ Test fixed

We can also easily add it to other forms if required?

### CODE REVIEW

**Comment by andrew** [comment]
We should also add some documentation to the readme for the ENV vars too at some point

**Comment by andrew** [comment]
Weirdly it's failing on a cucumber test because of the lack of ENV vars on travis, but the recapture part should be being skipped: https://github.com/ambethia/recaptcha/commit/394052277aca3c35130313d09754f8875c83c8cf

**Comment by nodunayo** [comment]
Strange because Travis by default runs in 'test' mode: https://docs.travis-ci.com/user/environment-variables/

**Comment by tomstuart** [comment]
I’ve never used any of this stuff, but it looks like [the environment](https://github.com/ambethia/recaptcha/blob/56679316e7731b596c3089768cad8021c8170cce/lib/recaptcha/verify.rb#L57-L60) only affects [the behaviour of `#verify_recaptcha`](https://github.com/ambethia/recaptcha/blob/56679316e7731b596c3089768cad8021c8170cce/lib/recaptcha/verify.rb#L9). You still need [a site key](https://github.com/ambethia/recaptcha/blob/9e475c87f3b1de9c6e8cd149419b0d97e7700c30/lib/recaptcha/client_helper.rb#L58) to [render `recaptcha_tags`](https://github.com/ambethia/recaptcha/blob/9e475c87f3b1de9c6e8cd149419b0d97e7700c30/lib/recaptcha/client_helper.rb#L15) in the view.

**Comment by tomstuart** [comment]
(So: I’d just set a dummy `RECAPTCHA_SITE_KEY` on Travis so that the view can render successfully.)

**Comment by nodunayo** [comment]
@tomstuart Hmm...that doesn't work on Travis, but it works locally...

**Comment by tomstuart** [comment]
@nodunayo How did you add the environment variable? I was expecting to see another commit here with [a change to `.travis.yml`](https://docs.travis-ci.com/user/environment-variables/#Defining-public-variables-in-.travis.yml), but I assume you did it in the Travis repository settings instead?

**Comment by nodunayo** [comment]
@tomstuart Ah, yes I did. Should I add it to .travis.yml instead? That's probably better so all configuration is in the code.

**Comment by tomstuart** [comment]
Well, it might not fix the build!, but yes, if it’s not sensitive information I think `.travis.yml` is preferable. For example, people will still get it in their Travis build if they fork the repo.

**Comment by nodunayo** [comment]
@tomstuart That worked! It seemed it didn't export the environment variables when I added it via the Travis repository settings!

Thanks a lot!

**Comment by andrew** [comment]
Thanks @tomstuart! 🎉

**Comment by nodunayo** [comment]
Yay, shipped!

**Pull request merged**
