### PR TITLE
Closes #33 Speaker index page is not one long list

### LINKED ISSUE #33: Speaker index page is not one long list
At the moment, when you visit the '/speakers' you get one long list, like so:

screen shot 2017-11-27 at 17 44 55

It would be great to find a way to better display the information. Perhaps columns?

Even better would be a solution that adapts to an ever-growing speaker list (🤞) rather than one that fits the number of speakers we currently have.

### PR DESCRIPTION
**Pull request by JulieLev**
#### What does this PR do?
* Splits speaker index list into three columns. Three selected instead of four to keep it reasonably tidy on small screens. 

##### Why was this work done? Is there a related Issue?
* #33 Speaker index page is not one long list

#### Where should a reviewer start?
* Final commit only is relevant 

#### Are there any manual testing steps?
* Change is visual, all tests still passing

---

#### Screenshots
screen shot 2017-12-07 at 15 08 12

#### Deployment instructions
* None

#### Database changes
* None

#### New ENV variables
* None

Hope this is what you were looking for! 

The only file that should be merged is the one in the final commit cfd93033600a93182f79a0d0bbbcef82a5faed89. 
Can you just cherry pick this or should I submit it a different way?

Thanks for the encouragement and clear opportunity to contribute.
All feedback welcomed!

### CODE REVIEW

**Comment by nodunayo** [comment]
Hey @JulieLev — will aim to have a look at this soon! Thank you!

**Comment by nodunayo** [comment]
Hi @JulieLev!

Finally having a chance to look at this. Thank you so much for your time.

It's said to be best to avoid using tables in HTML. They are really difficult to maintain and manipulate. It mixes up content (HTML) with layout concerns (CSS). Essentially, tables should be reserved for tabular data.

Given that, can we approach this differently?

Perhaps you can research a way to split the collection of Speakers into three, then make a css <div> with a specific class and use that to add columns.

In fact, I've used Skeleton CSS on the site. Check out the 'Grid' section of the page. It might give you some pointers!: http://getskeleton.com/#grid.
I reckon you can use their built in stuff to get the list into three columns.

Other points:

* Adding to the seeds is a great idea! Can you submit a separate PR for the addition of a seeds file? Maybe also add some fake proposals and submissions? Then we can also update the setup documentation on the README.md so that anyone setting up the site for the first time has a pre-filled DB. That would be wonderful!

* I've already submitted the uglifier update so when you resubmit that update should come through

Is that helpful?

Let me know if you have any questions!

**Comment by JulieLev** [comment]
Thank you Nadia, that's really clear, constructive feedback on the table! 
I will happily take a look at changing it with Skeleton. 

Also happy to add to the seeds (captchas, grrr...).

Not certain of timing just now but will be days rather than weeks.

So definitely helpful and thanks for the advice!

**Comment by nodunayo** [comment]
Hi @JulieLev,

Great. Glad it was helpful.

No rush — whenever works for you!

Speak soon,

Nadia

**Pull request closed without merging**
