### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by CrowdHailer**
This PR allows the project to be started in docker.

Instructions for running the server and tasks are included in the README.

### CODE REVIEW

**Comment by CrowdHailer** [comment]
I think the tests should be passing on this updated docker version. Not sure why they are just pending.

It's what I'm using locally and shouldn't have any affect on running it without docker.

**Comment by nodunayo** [comment]
Weird that it's not updating here.

Here's both your PRs with all specs passing:

Screenshot 2020-04-01 at 15 18 42

**Comment by CrowdHailer** [comment]
We'll this one is good to go. Will happily walk through it if your interested, but if your not using docker don't need to dwell on it

**Comment by nodunayo** [comment]
I haven't reviewed it all yet. Just thought I'd check the tests so you weren't concerned about it! I'll look later. Or maybe when we pair.

**Pull request merged**
